@echo off
echo Setting up the project...

echo Installing dependencies...
call npm install

echo Generating Prisma client...
call npx prisma generate

echo Creating database schema...
call npx prisma db push

echo Creating admin user...
call npm run dev:safe -- --port 3000 